export const environment = {
  production: false,
  apiKey:
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0NGU5YmQyMC0zZWQ1LTQ1MzMtYTdlZi1iMWYwOWJhNjVkMzgiLCJlbWFpbCI6InRpYWdvQGdtYWlsLmNvbSIsImdpdmVuX25hbWUiOiJUaWFnbyBTYW50aW5pIiwibmJmIjoxNjk3MDM3NzAxLCJleHAiOjE2OTcwNjY1MDEsImlhdCI6MTY5NzAzNzcwMSwiaXNzIjoiZUFnZW5kYSIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3QifQ.OT296WBqJLpt4ujIQL-9bq6mR46eDIECIZ_2vJ6at1M',
};
